version: "3"

services:
  tg-torrent-bot:
    image: fertkir/tg-torrent-bot:latest
    container_name: tg-torrent-bot
    restart: unless-stopped
    environment:
      - TELEGRAM_TOKEN=<telegram token> # TODO: replace with your telegram token
      - RUTRACKER_USERNAME=<rutracker username> # TODO: replace with your rutracker username
      - RUTRACKER_PASSWORD=<rutracker password> # TODO: replace with your rutracker password
