version: "3"

services:
  tg-torrent-bot:
    image: fertkir/tg-torrent-bot:latest
    restart: unless-stopped
    user: "1000:1000" # TODO replace without your user and group ids
    environment:
      - TELEGRAM_TOKEN=<telegram token> # TODO: replace with your telegram token
      - RUTRACKER_USERNAME=<rutracker username> # TODO: replace with your rutracker username
      - RUTRACKER_PASSWORD=<rutracker password> # TODO: replace with your rutracker password
      - TORRENTS_DIR=/torrents
      - COMPLETES_WATCHDIR=/completes
    volumes:
      - /home/username/Torrents:/torrents # TODO: replace with your .torrent files directory
      - completes:/completes
  transmission:
    image: linuxserver/transmission:latest
    environment:
      - PUID=1000  # TODO replace without your user id
      - PGID=1000  # TODO replace without your group id
      - TZ=Etc/UTC
      - DOCKER_MODS=fertkir/transmission-tg-torrent-bot:latest
    volumes:
      - transmission-config:/config
      - completes:/completes
      - /home/username/Downloads:/downloads # TODO: replace with your downloads directory
      - /home/username/Torrents:/watch # TODO: replace with your .torrent files directory
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"
    restart: unless-stopped
volumes:
  completes:
  transmission-config:
