version: "3"

services:
  tg-torrent-bot:
    image: fertkir/tg-torrent-bot:latest
    restart: unless-stopped
    environment:
      - TELEGRAM_TOKEN=<telegram token> # TODO: replace with your telegram token
      - RUTRACKER_USERNAME=<rutracker username> # TODO: replace with your rutracker username
      - RUTRACKER_PASSWORD=<rutracker password> # TODO: replace with your rutracker password
      - PROXY_TELEGRAM=false
      - PROXY_RUTRACKER=true
      - PROXY_HOST=shadowsocks
      - PROXY_PORT=34567
      - PROXY_PROTOCOL=socks5

  sslocal:
    image: ghcr.io/shadowsocks/sslocal-rust:latest
    restart: unless-stopped
    volumes:
      - /path/to/your/shadowsocks/config.json:/etc/shadowsocks-rust/config.json
