---
- name: Integrating tg-torrent-bot and transmission
  become: true
  block:
    - name: Including OS-specific variables
      ansible.builtin.include_vars: "Debian.yml"
      when: ansible_os_family == "Debian"

    - name: Installing required packages
      ansible.builtin.package:
        name:
          - npm
          - curl
          - "{{ transmission_package }}"
        state: present

    - name: Set up Transmission
      ansible.builtin.import_tasks: transmission.yml

    - name: Set up tg-torrent-bot
      ansible.builtin.import_tasks: tg-torrent-bot.yml

    - name: Starting services
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: started
        enabled: true
      with_items:
        - transmission-daemon
        - tg-torrent-bot
