---
- name: install npm
  ansible.builtin.package:
    name: npm
    state: present

- name: install tg-torrent-bot npm package globally
  community.general.npm:
    name: tg-torrent-bot
    global: true

- name: install transmission
  ansible.builtin.package:
    name: "{{ package_transmission }}"
    state: present

