---
- include_vars: "{{ ansible_distribution }}.yml"

- name: installing required packages npm
  ansible.builtin.package:
    name:
      - npm
      - "{{ packages.transmission }}"
    state: present

- name: install tg-torrent-bot npm package globally
  community.general.npm:
    name: tg-torrent-bot
    global: true

- name: start transmission-daemon to generate config
  ansible.builtin.systemd:
    name: transmission-daemon
    state: started

- name: stop transmission-daemon to be able to edit config
  ansible.builtin.systemd:
    name: transmission-daemon
    state: stopped

- name: update transmission settings.json
  block:
  - name: Slurp the json
    ansible.builtin.slurp:
    src: /var/lib/transmission/.config/transmission-daemon/settings.json
    register: slurped

  - name: before
    debug:
      var: json_contents

  - name: save contents to a variable
    set_fact:
      json_contents: "{{ slurped.content |  b64decode | from_json }}"

  - name: merge json with replacement values
    set_fact:
      json_contents: "{{ json_contents|combine({'script-torrent-done-enabled': true, 'script-torrent-done-filename': '/usr/bin/tg-torrent-bot', 'watch-dir': '/home/<youruser>/Torrents', 'watch-dir-enabled': true}, recursive=True) }}"

  - name: after
    debug:
      var: json_contents

  - name: write updated json
    copy:
      content: "{{ json_contents | to_nice_json(indent=2) }}"
      dest: /var/lib/transmission/.config/transmission-daemon/settings.json