---
- become: yes
  block:
    - debug:
        msg: "{{ lookup('env', 'USER') }}"
    - debug:
        msg: "{{ lookup('env', 'SUDO_USER') }}"
    - debug:
        msg: "{{ ansible_user_id }}"

    - name: installing required packages
      ansible.builtin.package:
        name:
          - npm
          - "{{ transmission.package }}"
        state: present

    - ansible.builtin.import_tasks: transmission.yml
    - ansible.builtin.import_tasks: tg-torrent-bot.yml

    - name: starting services
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: started
      with_items:
        - transmission-daemon
        - tg-torrent-bot
