---
- become: yes
  block:
    - include_vars: "{{ ansible_distribution }}.yml"

    - name: installing required packages
      ansible.builtin.package:
        name:
          - npm
          - "{{ transmission.package }}"
          - python-pip
        state: present

    - name: install jmespath
      ansible.builtin.pip:
        name: jmespath

    - ansible.builtin.import_tasks: transmission.yml
    - ansible.builtin.import_tasks: tg-torrent-bot.yml

    - name: starting services
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: started
      with_items:
        - transmission-daemon
        - tg-torrent-bot
