---
- include_vars: "{{ ansible_distribution }}.yml"

- name: install npm
  ansible.builtin.package:
    name: npm
    state: present

- name: install tg-torrent-bot npm package globally
  community.general.npm:
    name: tg-torrent-bot
    global: true

- name: install transmission
  ansible.builtin.package:
    name: "{{ packages.transmission }}"
    state: present

- name: start transmission-daemon to generate config
  ansible.builtin.systemd:
    name: transmission-daemon
    state: started

- name: stop transmission-daemon to be able to edit config
  ansible.builtin.systemd:
    name: transmission-daemon
    state: stopped
