---
- name: Install tg-torrent-bot npm package globally
  community.general.npm:
    name: tg-torrent-bot
    global: true

- name: Create tg-torrent-bot user
  ansible.builtin.user:
    name: tg-torrent-bot
    system: true
    create_home: false

- name: Copy tg-torrent-bot script
  ansible.builtin.copy:
    src: tg-torrent-bot
    dest: /usr/local/bin/
    mode: 0755

- name: Copy tg-torrent-bot.service
  ansible.builtin.copy:
    src: tg-torrent-bot.service
    dest: /etc/systemd/system/
    mode: 0644

- name: Create tg-torrent-bot configuration
  block:
    - name: Make sure /etc/tg-torrent-bot/ exists
      ansible.builtin.file:
        path: /etc/tg-torrent-bot/
        state: directory
        mode: 0755

    - name: Copy main.conf
      ansible.builtin.template:
        src: main.conf.j2
        dest: /etc/tg-torrent-bot/main.conf
        mode: 0644

- name: Creating /var/lib/tg-torrent-bot/
  ansible.builtin.file:
    path: /var/lib/tg-torrent-bot/
    state: directory
    owner: tg-torrent-bot
    group: tg-torrent-bot
    mode: 0755
