#!/usr/bin/with-contenv bash

# Creating script to notify tg-torrent-bot that a download has been complete
mkdir -p /completes
lsiown abc:abc /completes

sed -i '/script-torrent-done-enabled/c\    "script-torrent-done-enabled": true,' /config/settings.json
sed -i '/script-torrent-done-filename/c\    "script-torrent-done-filename": "/config/done-script",' /config/settings.json

echo '#!/bin/sh' > /config/done-script
echo 'TR_TORRENT_HASH_LOWERCASE=$(echo "$TR_TORRENT_HASH" | tr "[:upper:]" "[:lower:]")' >> /config/done-script
echo 'echo -n "$TR_TORRENT_NAME" > "/completes/$TR_TORRENT_HASH_LOWERCASE"' >> /config/done-script
chmod +x /config/done-script
lsiown abc:abc /config/done-script

# Customize downloads directories
if [[ -n "$DOWNLOAD_DIR" ]]; then
    rm -rf /downloads/complete
    sed -i "/download-dir/c\    \"download-dir\": \"$DOWNLOAD_DIR\"," /config/settings.json
    mkdir -p "$DOWNLOAD_DIR"
    lsiown abc:abc "$DOWNLOAD_DIR"
fi

if [[ -n "$INCOMPLETE_DIR_ENABLED" ]]; then
    rm -rf /downloads/incomplete
    sed -i "/incomplete-dir-enabled/c\    \"incomplete-dir-enabled\": \"$INCOMPLETE_DIR_ENABLED\"," /config/settings.json
fi
