name: Build all
on:
  workflow_dispatch:

jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm test
      - uses: JS-DevTools/npm-publish@v2
        id: publish
        with:
          token: ${{ secrets.NPM_TOKEN }}
    outputs:
      version: ${{ steps.publish.outputs.version }}

  docker:
    needs: npm
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: ./docker/tg-torrent-bot/Dockerfile
          push: true
          build-args: VERSION=${{ needs.npm.outputs.version }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tg-torrent-bot:latest
      -
        name: Update repo description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/tg-torrent-bot
          readme-filepath: ./docker/tg-torrent-bot/README.md
