name: Build all
on:
  workflow_dispatch:
    inputs:
      publish:
        description: 'Publish to npmjs'
        required: true
        default: true
        type: boolean
jobs:
  npm-build:
    uses: ./.github/workflows/npm-build.yml
    with:
      publish: ${{ inputs.publish }}
  docker-build:
    uses: ./.github/workflows/docker-build.yml
    with:
      version: ${{ needs.npm-build.version }}
