name: Publish to Ansible Galaxy
on:
  workflow_dispatch:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Publish to Ansible Galaxy
        uses: ansible/ansible-publish-action@v1.0.0
        with:
          api_key: ${{ secrets.GALAXY_API_KEY }}
          src_path: /ansible
